---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Cloning PlexGuide
      git:
        repo: "https://github.com/PGBlitz/Install"
        dest: /opt/pgstage
        version: "v8.5"
        force: yes
